import { PossibleTypesMap } from "@apollo/client";

/**
 * Generated by 'npm run possible-types'.
 */
const apolloPossibleTypes: PossibleTypesMap = {
    AccessControlled: ["Plan"],
    CorePlanItem: ["Plan", "PlanItem"],
    Ingredient: ["PantryItem", "Recipe"],
    Node: [
        "Favorite",
        "Label",
        "PantryItem",
        "Plan",
        "PlanItem",
        "PlannedRecipeHistory",
        "Recipe",
        "UnitOfMeasure",
        "User",
        "UserDevice",
    ],
    Owned: ["Acl", "Plan", "Recipe"],
};

export default apolloPossibleTypes;
