/**
 * Generated by 'npm run possible-types'.
 */
export default {
    AccessControlled: ["Plan"],
    CorePlanItem: ["Plan", "PlanItem"],
    Ingredient: ["PantryItem", "Recipe"],
    Node: [
        "Favorite",
        "Label",
        "PantryItem",
        "Plan",
        "PlanItem",
        "PlannedRecipeHistory",
        "Recipe",
        "UnitOfMeasure",
        "User",
    ],
    Owned: ["Acl", "Plan", "Recipe"],
};
