git mv Banner.js Banner.tsx
git mv CloseButton.js CloseButton.tsx
git mv CopyButton.js CopyButton.tsx
git mv DeleteButton.js DeleteButton.tsx
git mv Directions.js Directions.tsx
git mv EditButton.js EditButton.tsx
git mv FluxRoute.js FluxRoute.tsx
git mv FoodingerFab.js FoodingerFab.tsx
git mv ImageOrPreview.js ImageOrPreview.tsx
git mv LazyInfinite.js LazyInfinite.tsx
git mv LoadingIconButton.js LoadingIconButton.tsx
git mv LoadingIndicator.js LoadingIndicator.tsx
git mv LocalTextField.js LocalTextField.tsx
git mv Markdown.js Markdown.tsx
git mv NotFound.js NotFound.tsx
git mv OxfordList.js OxfordList.tsx
git mv PageBody.js PageBody.tsx
git mv PlaceholderIconButton.js PlaceholderIconButton.tsx
git mv PrivateRoute.js PrivateRoute.tsx
git mv Quantity.js Quantity.tsx
git mv RecipeInfo.js RecipeInfo.tsx
git mv SnackPack.js SnackPack.tsx
git mv Source.js Source.tsx
git mv SplitButton.js SplitButton.tsx
git mv colors.js colors.tsx
git mv icons.js icons.tsx