name: CI

on:
  # does NOT fire on retarget, only create!
  pull_request:
    branches:
      - master
      - beta
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: git diff --exit-code # ci and test shouldn't change anything
      - run: npm run format:write
      - run: git diff --exit-code # fail if Prettier wants any changes
      - run: npm run build
